Repository thienguen/barbell-labs, pull requests merged in 2024-02, with the labels that each got.

#44 🏯feat: refactor code for task 2.1 CHAT GPT Lab
  code_snippets/thien_calculator.py
Labels: documentation, enhancement

#46 🗓 feat: refactor to aye aye, task 2.2 CHAT GPT Lab
  code_snippets/thien_documentation.tsx
Labels: documentation

#48 ♻️ feat: include the "complex" code. task 2.3 CHAT GPT Lab
  code_snippets/thien_atomicBool.go
Labels: enhancement

#72 Add Timer component to be refactored in Task 2.1 of ChatGPT lab
  code_snippets/Marcos_Timer.tsx
Labels: enhancement

#74 File to add documentation for task 2.2 of ChatGPT lab
  code_snippets/Marcos_useOutsideClickDetector.tsx
Labels: documentation

#76 Add complex code for task 2.3 of ChatGpt lab
  code_snippets/Marcos_complex_code.ts
Labels: question
